// Dữ liệu mẫu các hãng xe và model tương ứng
export const carBrands = [
  {
    brand: "Toyota",
    models: [
      "Camry",
      "Corolla",
      "Vios",
      "Innova",
      "Fortuner",
      "Hilux",
      "Yaris",
      "RAV4",
      "Land Cruiser",
    ],
  },
  {
    brand: "Honda",
    models: [
      "Civic",
      "City",
      "CR-V",
      "HR-V",
      "Accord",
      "Jazz",
      "BR-V",
      "Pilot",
      "Odyssey",
    ],
  },
  {
    brand: "Ford",
    models: [
      "Ranger",
      "Everest",
      "Explorer",
      "Focus",
      "EcoSport",
      "Transit",
      "F-150",
      "Mustang",
      "Fiesta",
    ],
  },
  {
    brand: "Hyundai",
    models: [
      "Santa Fe",
      "Tucson",
      "Creta",
      "Accent",
      "Elantra",
      "Kona",
      "Palisade",
      "Venue",
      "Sonata",
    ],
  },
  {
    brand: "Kia",
    models: [
      "Sorento",
      "Sportage",
      "Seltos",
      "Carnival",
      "Cerato",
      "Morning",
      "Rio",
      "Stinger",
      "Optima",
    ],
  },
  {
    brand: "Mazda",
    models: [
      "CX-5",
      "CX-3",
      "Mazda3",
      "Mazda6",
      "CX-9",
      "BT-50",
      "CX-30",
      "Mazda2",
      "MX-5",
    ],
  },
  {
    brand: "Mitsubishi",
    models: [
      "Xpander",
      "Pajero",
      "Triton",
      "Outlander",
      "Attrage",
      "Mirage",
      "Eclipse Cross",
      "Lancer",
    ],
  },
  {
    brand: "Nissan",
    models: [
      "Navara",
      "Sunny",
      "Almera",
      "Terra",
      "Juke",
      "Qashqai",
      "Patrol",
      "X-Trail",
      "Altima",
    ],
  },
  {
    brand: "Suzuki",
    models: [
      "Swift",
      "Ertiga",
      "Ciaz",
      "Vitara",
      "XL7",
      "Jimny",
      "Celerio",
      "Baleno",
      "S-Presso",
    ],
  },
  {
    brand: "Chevrolet",
    models: [
      "Trailblazer",
      "Colorado",
      "Spark",
      "Cruze",
      "Malibu",
      "Captiva",
      "Orlando",
      "Aveo",
    ],
  },
  {
    brand: "Mercedes-Benz",
    models: [
      "C-Class",
      "E-Class",
      "S-Class",
      "GLC",
      "GLE",
      "A-Class",
      "B-Class",
      "CLA",
      "GLA",
    ],
  },
  {
    brand: "BMW",
    models: [
      "3 Series",
      "5 Series",
      "7 Series",
      "X3",
      "X5",
      "X1",
      "X7",
      "1 Series",
      "2 Series",
    ],
  },
  {
    brand: "Audi",
    models: ["A3", "A4", "A6", "Q5", "Q7", "Q3", "A8", "A1", "TT"],
  },
  {
    brand: "Volkswagen",
    models: [
      "Golf",
      "Passat",
      "Tiguan",
      "Polo",
      "Touareg",
      "Jetta",
      "Arteon",
      "T-Roc",
      "ID.4",
    ],
  },
  {
    brand: "Peugeot",
    models: [
      "208",
      "3008",
      "5008",
      "2008",
      "308",
      "408",
      "Partner",
      "Expert",
      "Boxer",
    ],
  },
  {
    brand: "Renault",
    models: [
      "Duster",
      "Captur",
      "Megane",
      "Clio",
      "Kadjar",
      "Koleos",
      "Logan",
      "Sandero",
      "Talisman",
    ],
  },
  {
    brand: "Isuzu",
    models: [
      "D-Max",
      "mu-X",
      "ELF",
      "FVR",
      "GIGA",
      "Forward",
      "N-Series",
      "F-Series",
    ],
  },
  {
    brand: "Lexus",
    models: ["RX", "LX", "GX", "ES", "NX", "LS", "UX", "LC", "IS"],
  },
  {
    brand: "Subaru",
    models: [
      "Forester",
      "Outback",
      "XV",
      "Impreza",
      "Legacy",
      "BRZ",
      "Ascent",
      "Crosstrek",
    ],
  },
  {
    brand: "Volvo",
    models: ["XC60", "XC90", "S60", "V60", "XC40", "S90", "V90", "C40", "XC70"],
  },
];

// Dữ liệu mẫu 20 xe để test
export const sampleCars = [
  {
    licensePlate: "30H-12345",
    brand: "Toyota",
    model: "Camry",
    year: 2022,
    seats: 5,
    transmission: "Automatic",
    fuel: "Gasoline",
    fuelConsumption: 7.5,
    address: "Hà Nội",
    description: "Xe gia đình, bảo dưỡng định kỳ",
    pricePerDay: 800000,
  },
  {
    licensePlate: "29A-67890",
    brand: "Honda",
    model: "Civic",
    year: 2021,
    seats: 5,
    transmission: "Automatic",
    fuel: "Gasoline",
    fuelConsumption: 6.8,
    address: "TP.HCM",
    description: "Xe thể thao, nội thất cao cấp",
    pricePerDay: 750000,
  },
  {
    licensePlate: "51B-11111",
    brand: "Ford",
    model: "Ranger",
    year: 2023,
    seats: 5,
    transmission: "Manual",
    fuel: "Diesel",
    fuelConsumption: 8.2,
    address: "Đà Nẵng",
    description: "Xe bán tải, phù hợp đi địa hình",
    pricePerDay: 900000,
  },
  {
    licensePlate: "43C-22222",
    brand: "Hyundai",
    model: "Santa Fe",
    year: 2022,
    seats: 7,
    transmission: "Automatic",
    fuel: "Gasoline",
    fuelConsumption: 9.1,
    address: "Cần Thơ",
    description: "SUV 7 chỗ, rộng rãi cho gia đình",
    pricePerDay: 850000,
  },
  {
    licensePlate: "14D-33333",
    brand: "Kia",
    model: "Sorento",
    year: 2021,
    seats: 7,
    transmission: "Automatic",
    fuel: "Gasoline",
    fuelConsumption: 8.5,
    address: "Hải Phòng",
    description: "SUV hiện đại, tiện nghi đầy đủ",
    pricePerDay: 780000,
  },
  {
    licensePlate: "61E-44444",
    brand: "Mazda",
    model: "CX-5",
    year: 2023,
    seats: 5,
    transmission: "Automatic",
    fuel: "Gasoline",
    fuelConsumption: 7.2,
    address: "Bình Dương",
    description: "SUV đô thị, thiết kế đẹp",
    pricePerDay: 820000,
  },
  {
    licensePlate: "92F-55555",
    brand: "Mitsubishi",
    model: "Xpander",
    year: 2022,
    seats: 7,
    transmission: "Manual",
    fuel: "Gasoline",
    fuelConsumption: 8.0,
    address: "Đồng Nai",
    description: "MPV 7 chỗ, tiết kiệm nhiên liệu",
    pricePerDay: 650000,
  },
  {
    licensePlate: "18G-66666",
    brand: "Nissan",
    model: "Navara",
    year: 2021,
    seats: 5,
    transmission: "Manual",
    fuel: "Diesel",
    fuelConsumption: 8.8,
    address: "Thanh Hóa",
    description: "Bán tải mạnh mẽ, bền bỉ",
    pricePerDay: 880000,
  },
  {
    licensePlate: "25H-77777",
    brand: "Suzuki",
    model: "Swift",
    year: 2023,
    seats: 5,
    transmission: "Manual",
    fuel: "Gasoline",
    fuelConsumption: 5.5,
    address: "Nghệ An",
    description: "Hatchback nhỏ gọn, dễ lái",
    pricePerDay: 550000,
  },
  {
    licensePlate: "36I-88888",
    brand: "Chevrolet",
    model: "Trailblazer",
    year: 2022,
    seats: 5,
    transmission: "Automatic",
    fuel: "Diesel",
    fuelConsumption: 8.3,
    address: "Quảng Ninh",
    description: "SUV Mỹ, nội thất rộng rãi",
    pricePerDay: 790000,
  },
  {
    licensePlate: "47J-99999",
    brand: "Mercedes-Benz",
    model: "C-Class",
    year: 2021,
    seats: 5,
    transmission: "Automatic",
    fuel: "Gasoline",
    fuelConsumption: 7.8,
    address: "Hà Nội",
    description: "Sedan hạng sang, đẳng cấp",
    pricePerDay: 1500000,
  },
  {
    licensePlate: "58K-00000",
    brand: "BMW",
    model: "3 Series",
    year: 2022,
    seats: 5,
    transmission: "Automatic",
    fuel: "Gasoline",
    fuelConsumption: 7.6,
    address: "TP.HCM",
    description: "Sedan thể thao, động cơ mạnh",
    pricePerDay: 1400000,
  },
  {
    licensePlate: "69L-11111",
    brand: "Audi",
    model: "Q5",
    year: 2023,
    seats: 5,
    transmission: "Automatic",
    fuel: "Gasoline",
    fuelConsumption: 8.1,
    address: "Đà Nẵng",
    description: "SUV cao cấp, công nghệ hiện đại",
    pricePerDay: 1600000,
  },
  {
    licensePlate: "70M-22222",
    brand: "Volkswagen",
    model: "Tiguan",
    year: 2022,
    seats: 5,
    transmission: "Automatic",
    fuel: "Gasoline",
    fuelConsumption: 7.9,
    address: "Bình Dương",
    description: "SUV Đức, chất lượng cao",
    pricePerDay: 850000,
  },
  {
    licensePlate: "81N-33333",
    brand: "Peugeot",
    model: "3008",
    year: 2021,
    seats: 5,
    transmission: "Automatic",
    fuel: "Diesel",
    fuelConsumption: 6.2,
    address: "Đồng Nai",
    description: "SUV Pháp, thiết kế tinh tế",
    pricePerDay: 780000,
  },
  {
    licensePlate: "90O-44444",
    brand: "Renault",
    model: "Duster",
    year: 2023,
    seats: 5,
    transmission: "Manual",
    fuel: "Gasoline",
    fuelConsumption: 7.3,
    address: "Thanh Hóa",
    description: "SUV giá rẻ, bền bỉ",
    pricePerDay: 600000,
  },
  {
    licensePlate: "12P-55555",
    brand: "Isuzu",
    model: "D-Max",
    year: 2022,
    seats: 5,
    transmission: "Manual",
    fuel: "Diesel",
    fuelConsumption: 9.0,
    address: "Nghệ An",
    description: "Bán tải Nhật, tải trọng cao",
    pricePerDay: 920000,
  },
  {
    licensePlate: "23Q-66666",
    brand: "Lexus",
    model: "RX",
    year: 2021,
    seats: 5,
    transmission: "Automatic",
    fuel: "Gasoline",
    fuelConsumption: 8.4,
    address: "Quảng Ninh",
    description: "SUV hạng sang, thoải mái",
    pricePerDay: 1800000,
  },
  {
    licensePlate: "34R-77777",
    brand: "Subaru",
    model: "Forester",
    year: 2023,
    seats: 5,
    transmission: "Automatic",
    fuel: "Gasoline",
    fuelConsumption: 7.7,
    address: "Hải Phòng",
    description: "SUV địa hình, hệ dẫn động 4WD",
    pricePerDay: 880000,
  },
  {
    licensePlate: "45S-88888",
    brand: "Volvo",
    model: "XC60",
    year: 2022,
    seats: 5,
    transmission: "Automatic",
    fuel: "Gasoline",
    fuelConsumption: 8.0,
    address: "Cần Thơ",
    description: "SUV an toàn, công nghệ tiên tiến",
    pricePerDay: 1200000,
  },
];
